# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  workflow_dispatch: {} 

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.9"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ultralytics onnx

    - name: Build test
      run: |
        python test.py
        
    - name: Open Pull Request
      uses: peter-evans/create-pull-request@v4
      with:
        commit-message: >
          Generated methods and types for GoTGramBot
        title: >
          Updated Methods and types for the lib
        body: >
          This is an automated PR.
        branch: test
        reviewers: Anandpskerala
        assignees: Anandpskerala
        labels: automated
        delete-branch: true
